# Generated by Django 2.2.10 on 2020-07-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('income', models.CharField(max_length=50)),
                ('edu', models.CharField(max_length=50)),
            ],
        ),
    ]
